---
# https://www.home-assistant.io/integrations/logger/
# Log Severities: notset, debug, info, warn, warning, error, fatal, critical
logger:
  default: error
  logs:
    # root: debug
    homeassistant: fatal
    homeassistant.core: info
    homeassistant.config: debug
    homeassistant.helpers.entity: error
    homeassistant.helpers.script: debug
    homeassistant.loader: error
    slixmpp.basexmpp: error
    slixmpp.stringprep: fatal
    aioharmony.harmonyclient: fatal
    pychromecast.socket_client: fatal
    custom_components.monitor_docker: fatal
    custom_components.monitor_docker.helpers: fatal
    custom_components.google_fit: debug
    custom_components.aio_geojson_query: debug
    # custom_components.gtfs_rt: debug

  filters:
    homeassistant:
      - "Error doing job: Task exception was never retrieved"
    homeassistant.loader:
      - "We found a custom integration"
    homeassistant.components.template.template_entity:
      - "Template loop detected while processing event"
    homeassistant.components.media_player:
      - "Updating spotify media_player took longer than the scheduled update interval 0:00:30"
    homeassistant.helpers.entity:
      - "Update of media_player.spotify_thomas_baxter is taking over 10 seconds"
    spotipy.client:
      - "Max Retries reached"
    custom_components.ical:
      - "Exception can't compare datetime.datetime to datetime.date in starts/ends"
    homeassistant.components.waze_travel_time.sensor:
      - "Error on retrieving data: empty response"
    TransportNSW.transportnsw:
      - "No stop events for this query"
    homeassistant.components.recorder:
      - "Unhandled database error while processing task EventTask"
    custom_components.monitor_docker.helpers:
      - "Can not determine network usage for container ('networks')"
      - "No 'networks' found in raw packet"
      - "Too many errors on 'networks' stats, disabling monitoring"
